return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    preset = 'classic',
    spec = {
      { '<leader>f', group = '[F]ile' },
      { '<leader>l', group = '[L]sp' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>v', group = '[V]isual' },
    },
    win = {
      padding = { 0, 2 },
      no_overlap = false,
    },
    icons = {
      mappings = false,
      keys = {
        Up = '<up>',
        Down = '<down>',
        Left = '<left>',
        Right = '<right>',
        C = '<ctrl>',
        M = '<alt>',
        D = '<meta>',
        S = '<shift>',
        CR = '<cr>',
        Esc = '<esc>',
        ScrollWheelDown = '󱕐 ',
        ScrollWheelUp = '󱕑 ',
        NL = '<cr>',
        BS = '<bs>',
        Space = '<space>',
        Tab = '<tab>',
        F1 = 'F1',
        F2 = 'F2',
        F3 = 'F3',
        F4 = 'F4',
        F5 = 'F5',
        F6 = 'F6',
        F7 = 'F7',
        F8 = 'F8',
        F9 = 'F9',
        F10 = 'F10',
        F11 = 'F11',
        F12 = 'F12',
      },
    },
  },
}
